MiniFb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("SocialApp.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from django_email_verification import urls as mail_urls


app_name = 'socialapp'
urlpatterns = [
    path('', views.registerPage),
    path('login/', views.userLogin, name="login"),
    path('registration_page/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name="logout"),
    path('newpost/', views.newPost, name="newpost"),
    path('userpostspage/', views.userPostsPage, name='userposts'),
    path('postdetailpage/<int:id>', views.postdetail, name='postdetail'),
    path('updatepost/<int:id>/', views.updatePost, name='updatepost'),
    path('deletepost/<int:id>/', views.deletePost, name='deletepost'),
    path('verifylogin/', views.verifyEmail),
    path('emailduplicationcheck', views.emailDuplicationChecker, name='emailduplicationcheck'),
]

SocialApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Users(AbstractUser):
    class Meta:
        verbose_name = "CustomUser"
        verbose_name_plural = "CustomUsers"


class BlogPost(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    image = models.ImageField()
    user = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.title

SocialApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Users, BlogPost
from django.forms import ModelForm
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = Users
        fields = ['username', 'email', 'password1', 'password2']

    # def clean_password2(self):


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'description', 'image']
        # def __init__(self, *args, **kwargs):
        #     id = kwargs.pop('id')
        #     super(PostUpdateForm, self).__init__(*args, **kwargs)
        #     self.fields['id'].queryset = BlogPost.objects.filter(id=id)

SocialApp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from MiniFb import settings
from .forms import CreateUserForm, PostUpdateForm
from .models import *
from django.core.mail import send_mail
from MiniFb.settings import *
from django.contrib.sessions.models import Session
import json

def index(request):
    return HttpResponse("Testing")


def registerPage(request):
    if request.session.has_key('is_logged'):
        return redirect('socialapp:userposts')
    else:
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                # subject = 'Email Verification'
                # message = 'http://127.0.0.1:8000/verifylogin/?token=1234'
                # recepient = request.POST.get('email')
                # send_mail(subject,
                #           message, EMAIL_HOST_USER, [recepient], fail_silently=False)
                return redirect('socialapp:login')
        form = CreateUserForm()
        context = {}
        context['form'] = form
        return render(request, 'register.html', context)


def userLogin(request):
    # if request.session.has_key('is_logged'):
    #     return redirect('socialapp:userposts')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        rememberMe = False
        try:
            rememberMe = request.POST['rememberme']
            rememberMe = True
        except:
            rememberMe = False
        print('rem me:', rememberMe)
        usr = authenticate(request, username=username, password=password)
        if usr is not None:
            login(request, usr)
            request.session['is_logged'] = True
            if rememberMe==True:
                request.session.set_expiry(3600*24)
            else:
                request.session.set_expiry(3600)
            return redirect('socialapp:userposts')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'login.html', context)


@login_required
def logoutUser(request):
    logout(request)
    return redirect('socialapp:login')


@login_required
def newPost(request):
    if request.method == 'POST':
        form = PostUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect('socialapp:userposts')
        else:
            context={}
            context["form"]=form
            return render(request, 'new_update_post.html', context)
    form = PostUpdateForm()
    context = {'form': form}
    return render(request, 'new_update_post.html', context)


@login_required
def userPostsPage(request):
    posts = BlogPost.objects.filter(user=request.user)
    print("posts count: ", posts.count())
    context = {'posts': posts, 'media_url': settings.MEDIA_URL}
    return render(request, 'user_posts.html', context)


@login_required
def postdetail(request, id):
    post = BlogPost.objects.filter(id=id)
    context = {'post': post, 'media_url': settings.MEDIA_URL}
    return render(request, 'post_detail.html', context)


@login_required
def updatePost(request, id):
    inst = BlogPost.objects.get(id=id)
    if request.method == 'POST':
        form = PostUpdateForm(request.POST, request.FILES, instance=inst)
        if form.is_valid():
            form.save()
            print("this is valid")
            return redirect('socialapp:userposts')
        else:
            print("this is invalid")
            return redirect('socialapp:newpost')
        # title = request.POST.get('title')
        # description = request.POST.get('description')
        # try:
        #     image = request.FILES.get('image')
        #     BlogPost.objects.filter(id=id).update(title=title, image=image, description=description)
        # except:
        #     BlogPost.objects.filter(id=id).update(title=title, description=description)

    form = PostUpdateForm(request.POST or None, instance=inst)
    context = {'form': form, 'media_url': settings.MEDIA_URL}
    return render(request, 'new_update_post.html', context)


@login_required
def deletePost(request, id):
    BlogPost.objects.filter(id=id).delete()
    return redirect('socialapp:userposts')


def verifyEmail(request):
    key = 1234
    token = request.GET.get('token')
    if int(token) == key:
        return redirect('socialapp:login')
    else:
        return HttpResponse('invalid token')

def emailDuplicationChecker(request):
    temp = Users.objects.filter(email=request.GET.get('email')).count()
    if temp > 0:
        return JsonResponse({"status": False})
    else:
        return JsonResponse({"status": True})

SocialApp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background-image: url('{% static "images/bg.jpg"%}');
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>
							<div>
								<input type="checkbox" id="rememberme" name="rememberme" value="Remember me">
								<label for="rememberme"> Remember me</label><br>
							</div>
							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'socialapp:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

SocialApp/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta name=”viewport” content="width=device-width, initial-scale=1.0">
	<link rel=”stylesheet” href="{% static 'css/bootstrap.css'%}">
	<link rel=”stylesheet” href="{% static 'css/bootstrap-responsive.css'%}">


	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<style>
		.ftr {
			width: 100%;
			margin-top: 25px;
			bottom: 0;
			left: 0;
			text-align: center;
			padding: 10px;
		}

		.bg{
			background-image: url('{% static "images/bg.jpg"%}');
			background-repeat: no-repeat;
			background-attachment: fixed;

		}
	</style>
</head>

<body class="bg">
	{% include 'navbar.html' %}
	{% block content %}


	
	{% endblock %}
	<footer class="footer text-center bg-primary bg-dark ftr">
		<h5>copyright &copy; Argon</h5>
	</footer>
</body>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

{% block extra_js%}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

</html>

SocialApp/templates/navbar.html
{% load static %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
    <style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <img src="{% static 'img.png' %}" style="width:80px; height:80px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'socialapp:userposts' %}">My Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'socialapp:newpost' %}">Post a Memory</a>
      </li>
    </ul>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span>
<!--  <span ><a  class="hello-msg" href="{% url 'socialapp:register' %}">Register</a></span>-->
  <span ><a  class="hello-msg" href="{% url 'socialapp:logout' %}">Logout</a></span>

</nav>

SocialApp/templates/new_post.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<meta charset="UTF-8">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style>
        .btn {
            background-color: orange;
            border: 2px solid black;
            color: white;
        }

        .lbl {
            color: orange;
        }
    </style>
</head>
<title>New Post</title>

<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <label style="display:block;" class="mt-2 lbl">Title</label>
                {{form.instance.title | default_if_none:form.title}}
                <!-- <input type="text" name="title"> -->
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 lbl mt-5">
                <img id="img" src="{{media_url}}/{{form.instance.image}}" style="width:100px; height:100px;">
                <input type="file" id="id_image">
                <!-- {{form.image}} -->
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label style="display:block;" class="mt-5 lbl">Description</label>
                {{form.instance.description | default_if_none:form.description}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mt-5">
                <input type="submit" value="Post" class="btn">
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block extra_js%}
<script>
    $("#id_image").on('change',function () {
        $("#img").attr('src', window.URL.createObjectURL(this.files[0])) 
        })
</script>
{% endblock %}

SocialApp/templates/new_update_post.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<meta charset="UTF-8">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style>
        .btn {
            background-color: orange;
            border: 2px solid black;
            color: white;
        }

        .lbl {
            color: orange;
        }
    </style>
</head>
<title>New Post</title>

<form method="POST" action="" enctype="multipart/form-data">
    {{form.errors}}
    {% csrf_token %}
    <div class="container">

        {% for field in form %}
        <div class="row">
            <div class="col-md-6">
                <label style="display:block;" class="mt-2 lbl">{{field.label}}</label>
                {{field}}
            </div>
        </div>
        {% endfor %}
        <div class="row">
            <div class="col-md-6 lbl mt-5">
                <img id="img" src="{{media_url}}/{{form.instance.image}}" style="width:100px; height:100px;">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mt-5">
                <input type="submit" value="Post" id="btnPost" class="btn">
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block extra_js%}
<script>
    // $("input type=[file]").val('{{form.instance.image}}')
    $("#id_image").on('change', function () {
        $("#img").attr('src', window.URL.createObjectURL(this.files[0]))
    })
</script>
{% endblock %}

SocialApp/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
		integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<!-- <link rel="stylesheet" href="{% static 'js/javascript.js' %}"> -->

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background-image: url('{% static "images/bg.jpg"%}');
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title {
			color: #fff;
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}

		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.login_container {
			padding: 0 2rem;
		}

		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
	</style>

</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span> <span
									id="error-name"></span>
							</div>
							{{form.username}}
							{{form.errors.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span> <span
									id="error-email"></span>
							</div>
							{{form.email}}
							{{form.errors.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span> <span
									id="error-password"></span>
							</div>
							{{form.password1}}
							{{form.errrors.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span> <span
									id="error-password2"></span>
							</div>
							{{form.password2}}
							{{form.errors.password2}}

						</div>


						<div class="d-flex justify-content-center mt-3 login_container">
							<input class="btn login_btn" type="submit" value="Register Account">
						</div>

					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'socialapp:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
<script>
	//Query All input fields
	var form_fields = document.getElementsByTagName('input')
	form_fields[1].placeholder = 'Username..';
	form_fields[2].placeholder = 'Email..';
	form_fields[3].placeholder = 'Enter password...';
	form_fields[4].placeholder = 'Re-enter Password...';


	for (var field in form_fields) {
		form_fields[field].className += ' form-control'
	}

	$("#id_email").on("blur", function (e) {
		var mailformat = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
		if (mailformat.test(String($("#id_email").val()))) {
			emailChecker();
			//return true;
		}
		else {
			document.getElementById('error-email').innerHTML = "Invalid email address";
			$("#id_email").focus();
			//return false;
		}
	});

	function emailChecker() {

		var email = $('#id_email').val();
		$.ajax({
			url: "{% url 'socialapp:emailduplicationcheck'%}",
			method: 'GET',
			data: { email: email },
			dataType: 'json',
			success: (function (response) { // on success
				if (response['status']) {
					document.getElementById('error-email').innerHTML = "Unique email. You are good to go";
				}
				else {
					document.getElementById('error-email').innerHTML = "Thit Email address already exists";

				}

			}),
			error: (function (error) { // on error
				console.log("error", error)
			})
		});
		// .done(function (response) { // on success
		//     // var obj = JSON.parse(response);
		//     console.log("=email exists",response.status)
		// })
		// .fail(function (xhr, errmsg, err) { // on error
		//     console.log("email not exist")

		//     console.log(errmsg);
		// });
	}
</script>

</html>

SocialApp/templates/user_posts.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style>
        button {
            width: 80px;
            background-color: orange;
            color: white;

        }

        .post-content {
            border: 2px solid rgb(105, 184, 105);
            margin: 5px;
            padding: 10px;
            background-color: rgba(255, 255, 255, 0.493);
        }
    </style>
</head>
<title>Posts</title>

<div class="container">
    <div class="row">
        <strong style="color: whitesmoke;">My Posts</strong>
        <hr style="color: green;">
    </div>
    {%for p in posts %}
    <div class="post-content">
        <div class="row">
            <div class="col-md-4 mt-3">
                <h4 style="color: orange;">{{p.title}}</h4>
                <hr style="width:70%;text-align:left;margin-left:0">
                {{p.description}}
            </div>
            <div class="col-md-4 mt-3">
                <img src="{{media_url}}/{{p.image}}" style="width:200px; height:200px; float:right;">
            </div>
            <div class="col-md-4 mt-3">
                <button type="submit" onclick="location.href = '{% url 'socialapp:postdetail' p.id %}'">View</button>
                <button type="submit" onclick="location.href = '{% url 'socialapp:updatepost' p.id %}'">Update</button>
                <button type="submit" onclick="location.href = '{% url 'socialapp:deletepost' p.id %}'">Delete</button>
                
            </div>
        </div>

        <!-- <div class="row">
            <div class="col-md-1">
            </div>

            <div class="col-md-1">
            </div>

            <div class="col-md-1">
            </div>
        </div> -->
    </div>

    {%endfor%}
</div>
{% endblock %}